In [72]:
import numpy as np
import pandas as pd
from sklearn import linear_model
!pip install word2number
from word2number import w2n

In [73]:
df=pd.read_csv('hiring.csv')

In [74]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [75]:
df.isnull()


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        True                  False                       False      False
1        True                  False                       False      False
2       False                  False                       False      False
3       False                  False                       False      False
4       False                  False                       False      False
5       False                  False                       False      False
6       False                   True                       False      False
7       False                  False                       False      False

In [76]:
df.experience=df.experience.fillna('zero')

In [77]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [78]:
df = df.rename(columns={'test_score(out of 10)': 'TestScore'})
df = df.rename(columns={'interview_score(out of 10)': 'InterviewScore'})
df = df.rename(columns={'salary($)': 'Salary'})

In [79]:
df

experience  TestScore  InterviewScore  Salary
0       zero        8.0               9   50000
1       zero        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        NaN               7   72000
7     eleven        7.0               8   80000

In [80]:
df.TestScore=df.TestScore.fillna(df.TestScore.median())
df

experience  TestScore  InterviewScore  Salary
0       zero        8.0               9   50000
1       zero        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        8.0               7   72000
7     eleven        7.0               8   80000

In [81]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  TestScore  InterviewScore  Salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        8.0               7   72000
7          11        7.0               8   80000

In [82]:
features=df.drop('Salary',axis='columns')
lables=df.Salary

In [83]:
reg = linear_model.LinearRegression()
reg.fit(features,lables)

LinearRegression()

In [84]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [85]:
reg.intercept_

17737.26346433771

In [86]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [89]:
2812.95487627*2+1845.70596798*9+1845.70596798*6+17737.26346433771

51048.76273657771

In [88]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [90]:
2812.95487627*12+1845.70596798*10+2205.24017467*10+17737.26346433771

92002.1834060777